FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.7-build

ENV DEBUG=1

RUN [ "cross-build-start" ]

WORKDIR /usr/src/app

RUN install_packages dnsmasq wireless-tools gdb python3-dev wget netcat sqlite
RUN pip3 install paho-mqtt certifi RPi.GPIO



# Copy
COPY ./src/ . 

# Enable udevd so that plugged dynamic hardware devices show up in our container.
ENV UDEV=1

RUN [ "cross-build-end" ]

# start
CMD ["python", "./test.py"]
